name: My first pipeline

on:
  push

jobs:
  run_scripts:              #### Название job
    runs-on: ubuntu-22.04
    steps:
      - name: echo simple text
        run: echo "This is my first Github pipeline"
    
      - name: prepare ssh keys
        run: |
          ## Download ssh key to .ssh/
          mkdir -m 700 ~/.ssh
          echo -e "${{ secrets.CICD_SSH_PRIV_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          ## Allow connection to github
          cat << EOF >> ~/.ssh/config
          Host github.com
              StrictHostKeyChecking no
              UserKnownHostsFile=/dev/null
              ForwardAgent yes
          EOF
    
      - name: clone repository
        run: git clone git@github.com:networkthor/cicd-lesson-2gr.git
    
      - name: show date
        run: |
            ls -la
            cd cicd-lesson-2gr
            scripts/test-scripts.sh